### ISSUE TITLE
When I'm trying to execute this code its giving error like

### ISSUE THREAD

**Issue by adhit159** [palmerabollo/bingspeech-api-client#11]
down vote
favorite
When I'm trying to execute this code its giving error like

(node:3784) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec tion id: 1): Error: Voice recognition failed miserably: socket hang up

var fs = require('fs');
var bing = require('C:\\Program Files\\nodejs\\node_modules\\bingspeech-api-client\\lib\\client.js');

var audioStream = fs.createReadStream('d:\\node.wav'); 

var subscriptionKey = 'xxxxxxxxxxxxxxxxx';

var client = new bing.BingSpeechClient(subscriptionKey);
client.recognizeStream(audioStream)
.then(response => console.log(response.results[0].name));

http://stackoverflow.com/questions/42570738/speech-to-text-bing-speech-api-azure

**Comment by palmerabollo** [comment]
@adhit159 Works for me and for [some other users](https://stackoverflow.com/questions/42570738/speech-to-text-bing-speech-api-azure), too. Are you still facing this issue? Reopen if needed.

**Comment by concordion2k** [comment]
Does this library use WebSockets?

**Comment by palmerabollo** [comment]
No. It uses tradicional HTTP requests.
