### ISSUE TITLE
Issue with `import`

### ISSUE THREAD

**Issue by pietrop** [palmerabollo/bingspeech-api-client#12]
To get the example code working I had to change the first line to: 

```js
const { BingSpeechClient, VoiceRecognitionResponse } = require('bingspeech-api-client');
```

I think at present node does not support import. As mentioned on [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/import)

>Note: This feature[`import`] is only beginning to be implemented in browsers natively at this time. It is implemented in many transpilers, such as the Traceur Compiler, Babel, Rollup or Webpack.

**Comment by palmerabollo** [comment]
Yes, you're right. The examples in the README are for typescript code.
I'll add a section to the README when I find some time. Feel free to send a pull request to improve the docs. Thanks.

**Comment by pietrop** [comment]
Ok thanks @palmerabollo sending you a pull request with an updated `README` now. Let me know if that works for you.

**Comment by palmerabollo** [comment]
Perfect, thanks Pietro.
