### ISSUE TITLE
Module is not able to do Speech to text conversion -  (STT ) Conversion - Returning 404 response with invalid token

### ISSUE THREAD

**Issue by iPrav** [palmerabollo/bingspeech-api-client#15]
After much debugging I found out this is because of missing 'Ocp-Apim-Subscription-Key'.

Response in node.js 👍 

(node:80377) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Voice recognition failed miserably: Wrong status code 404 in Bing Speech API / token

For some reason this is not getting set even after an object was creating by passing the 'MICROSOFT_BING_SPEECH_KEY'

**Comment by palmerabollo** [comment]
@iPrav are you sure you are passing a valid key when you create the `BingSpeechClient`?

```typescript
let client = new BingSpeechClient(yourSubscriptionKeyHere);
```
Could you share the relevant parts of the code?

**Comment by iPrav** [comment]
Hi,

Relevant parts of the code at the bottom:

Yes. I have checked it multiple times. 

In fact  I have hardcoded the **Ocp-Apim-Subscription-Key** in the client.js file and it is working OK for your example.wav file.

If I use a different example .wav file ( 10-15 sec conversations )  it is coming is only part of the conversation. 

For example if I use (Bargain not WAV file  ) in the link ( http://www.wavsource.com/movie_stars/davis.htm )  for the test it is printing the speech as below  ( not the complete speech in the audio ).

Do I need to set the client to converstion mode somewhere ? 

**Output from the code for above .wav file :** 

{ version: '3.0',
  header:
   { status: 'success',
     scenario: 'ulm',
     name: 'you\'re not much of a bother you know you',
     lexical: 'you\'re not much of a bother you know you',
     properties:
      { requestid: '7b8918d9-f492-45b9-abe4-466f36287c70',
        HIGHCONF: '1' } },
  results:
   [ { scenario: 'ulm',
       name: 'you\'re not much of a bother you know you',
       lexical: 'you\'re not much of a bother you know you',
       confidence: '0.9048215',
       properties: [Object] } ] }


****Relevant parts of the code :**** 

let audioStream = fs.createReadStream(__dirname + '/example.wav');

// Bing Speech Key (https://www.microsoft.com/cognitive-services/en-us/subscriptions)
let subscriptionKey = new BingSpeechClient(process.env.MICROSOFT_BING_SPEECH_KEY);

let client = new BingSpeechClient(subscriptionKey);

var wave = fs.readFileSync(__dirname + '/example.wav');
client.recognize(wave).then(result => {
  console.log('Speech To Text completed');
  console.log(result)
  console.log('\n');
});

**Comment by palmerabollo** [comment]
Everything looks ok. I think BING might be detecting the end of the file because it's a bit noisy...
