### ISSUE TITLE
Add support for the Saudi Arabian dialect

### ISSUE THREAD

**Issue by CarlousF** [palmerabollo/bingspeech-api-client#21]
Needed this for a project recently, and ended up [making a fork](https://github.com/CarlousF/bingspeech-api-client-saudi) from this repo and adding it myself, but would be great if support for the Saudi Arabian dialect was added back into this project.

**Comment by palmerabollo** [comment]
@CarlousF thanks. Could you please send a PR so I can add your changes?

**Comment by CarlousF** [comment]
@palmerabollo No probs, have made a [pull request](https://github.com/palmerabollo/bingspeech-api-client/pull/22) for this.

**Comment by CarlousF** [comment]
Closing this as the pull request has now been merged.
